# Generated by Django 4.1 on 2022-08-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('category', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee'), ('Business', 'Business'), ('Other', 'Other')], max_length=40)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
