# Generated by Django 4.1 on 2022-08-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=30, null=True)),
                ('amount', models.IntegerField()),
                ('importance', models.CharField(choices=[('important', 'important'), ('normal', 'normal'), ('less important', 'less important')], max_length=30)),
                ('tags', models.CharField(choices=[('Food', 'Food'), ('Social Life', 'Social Life'), ('Self-development', 'Self-development'), ('Transportation', 'Transportation'), ('Household', 'Household'), ('Apparel', 'Apparel'), ('Health', 'Health'), ('Education', 'Education'), ('Waste', 'Waste'), ('Other', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.expense'),
        ),
    ]
